### ISSUE TITLE
Update Dredd Version

### ISSUE THREAD

**Issue by garyluu** [ga4gh/tool-registry-validator#5]
Currently the Dredd version is 4.7.0 and does not support OpenAPI 3.  In the future, it should be updated to a newer Dredd version that does.  There was an attempt at 8.0.3 but the version seems to believe the Dockstore /tools endpoint with a limit greater than 35 returns a base64 body instead of utf-8.  It's likely that it's a Dredd issue

**Comment by denis-yuen** [comment]
@garyluu please link to the issue you found in the dredd repo

**Comment by garyluu** [comment]
https://github.com/apiaryio/dredd/issues/1254

**Comment by garyluu** [comment]
Turns out the issue is https://github.com/dockstore/dockstore/issues/2912 and not quite a Dredd issue
